{% set name = "yaqd-edaq" %}
{% set version = "2021.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yaqd-edaq-{{ version }}.tar.gz
  sha256: a3d14cc919482daa2d5aacd51dec957634887b6a6041663ccea91a93b2abb116

build:
  number: 1
  noarch: python
  entry_points:
    - yaqd-edaq-isopod=yaqd_edaq._edaq_isopod:EdaqIsoPod.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - flit
    - yaqd-core >=2020.05.1
    - pyserial

test:
  imports:
    - yaqd_edaq
  commands:
    - pip check
    - yaqd-edaq-isopod --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://yaq.fyi
  summary: yaq daemons for edaq sensor recording systems
  dev_url: https://gitlab.com/yaq/yaqd-edaq
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
